[build-system]
requires = ["setuptools>=83.0.0"]
build-backend = "setuptools.build_meta"

[project]
name    = "python-lightsout"
version = "2.0.0"
requires-python = ">=3.13"
description = "A Python package for Lights Out."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
keywords = ["lightsout"]

[project.urls]
Repository = "https://github.com/MingMinNa/Python-LightsOut"

[project.optional-dependencies]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.3"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.coverage.run]
source = ["src/lightsout"]